services:
  user-webflux:
    build: .
    container_name: user-webflux
    environment:
      - SERVER_PORT=8181
      - MONGODB_URI=mongodb://user:pass@mongo:27017/minisocialdb?authSource=admin
      - MONGODB_DATABASE=minisocialdb
    ports:
      - "8181:8181"
    networks:
      - reactive-ms-network

networks:
  reactive-ms-network:
    external: true