spring:
    application:
        name: ingestion
#     cloud:
#         config:
#             discovery:
#                 enabled: true
#                 service-id: config
#             request-connected-timeout: 5000
#             request-read-timeout: 5000
#             fail-fast: true
#             retry:
#                 max-attempts: 10
#                 initial-interval: 1000
#                 max-interval: 2000
#                 multiplier: 1.1
#     config:
#         import: "optional:configserver:"
    cassandra:
        contact-points: localhost
        port: 9042
        local-datacenter: datacenter1
        keyspace-name: ingestion_flux
        schema-action: create_if_not_exists
    data:
        redis:
            database: 1
            host: localhost
            port: 6379

# eureka:
#     client:
#         fetch-registry: true
#         register-with-eureka: true
#         service-url:
#             defaultZone: http://discovery1:8761/eureka,http://discovery2:8762/eureka
#     instance:
#         prefer-ip-address: true